apiVersion: v1
kind: ConfigMap
metadata:
  name: activemq-config
data:
  ACTIVEMQ_CONFIG_NAME: activemq
  ACTIVEMQ_CONFIG_DEFAULTACCOUNT: "false"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: activemq-statefulset
spec:
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      labels:
        app: activemq
    spec:
      containers:
      - name: activemq
        image: webcenter/activemq:5.14.3
        ports:
        - containerPort: 61616
          name: tcp
        - containerPort: 8161
          name: admin
        env:
        - name: ACTIVEMQ_NAME
          valueFrom:
            configMapKeyRef:
              name: activemq-config
              key: ACTIVEMQ_CONFIG_NAME
        - name: ACTIVEMQ_DEFAULT_ACCOUNT
          valueFrom:
            configMapKeyRef:
              name: activemq-config
              key: ACTIVEMQ_CONFIG_DEFAULTACCOUNT
---
apiVersion: v1
kind: Service
metadata:
  name: activemq-service
  labels:
    app: activemq
spec:
  type: NodePort
  selector:
    app: activemq
  ports:
  - name: amq
    protocol: TCP
    port: 61616
    targetPort: 61616
    nodePort: 30009
  - name: web
    protocol: TCP
    port: 8161
    targetPort: 8161
    nodePort: 30010
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: activemq-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: activemq.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: activemq-service
            port:
              number: 8161
